# See /LICENSE for more information.
# This is free software, licensed under the Apache License 2.0.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI WebAuthn Passkey Authentication
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
