#!/bin/sh

PLUGIN_UUID="25e715cf23e44e35bc6763e804d85b85"

touch /etc/config/luci_plugins

uci -q get luci_plugins.global >/dev/null || {
	uci set luci_plugins.global=global
	uci set luci_plugins.global.enabled='0'
}

uci -q get luci_plugins.global.auth_login_enabled >/dev/null || {
	uci set luci_plugins.global.auth_login_enabled='0'
}

uci -q get "luci_plugins.${PLUGIN_UUID}" >/dev/null || {
	uci set "luci_plugins.${PLUGIN_UUID}=auth_login"
	uci set "luci_plugins.${PLUGIN_UUID}.enabled=0"
	uci set "luci_plugins.${PLUGIN_UUID}.name=WebAuthn Passkey"
}

uci commit luci_plugins

exit 0
